...............F.F......F
======================================================================
FAIL: test_predict_1 (__main__.TestNetflix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestNetflix.py", line 110, in test_predict_1
    self.assertEqual(3.6, rating)
AssertionError: 3.6 != 3.5

======================================================================
FAIL: test_predict_3 (__main__.TestNetflix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestNetflix.py", line 118, in test_predict_3
    self.assertEqual(3.2, rating)
AssertionError: 3.2 != 3.1

======================================================================
FAIL: test_solve_1 (__main__.TestNetflix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestNetflix.py", line 221, in test_solve_1
    self.assertEqual(w.getvalue(), "1:\n3.7\n3.5\n3.6\nRMSE: 0.48")
AssertionError: '1:\n3.7\n3.4\n3.6\nRMSE: 0.51' != '1:\n3.7\n3.5\n3.6\nRMSE: 0.48'
  1:
  3.7
- 3.4
?   ^
+ 3.5
?   ^
  3.6
- RMSE: 0.51?         ^^
+ RMSE: 0.48?         ^^


----------------------------------------------------------------------
Ran 25 tests in 6.387s

FAILED (failures=3)
